name: 'Azure Monitor Action'
description: 'Send Azure Monitor custom logs from GitHub Actions'
author: 'hoisjp'
inputs:
  workspace-id:
    required: true
    description: 'workspace ID of your Log Analytics workspace'
  agent-key:
    required: true
    description: 'Agent key of your Log Analytics workspace'
  json-body:
    required: true
    description: 'JSON string to post to Log Analytics'
runs:
  using: 'node12'
  main: 'dist/index.js'
